image: microsoft/dotnet:latest

variables:
   # AWS_ACCESS_KEY_ID: "YUOUR_AWS_ACCESS_KEY_ID"
   # AWS_SECRET_ACCESS_KEY: YOUR_AWS_SECRET_ACCESS_KEY
    S3_BUCKET_NAME: "dotnetapilambda-bucket"

before_script:
    - cd DotNetApiLambda
    - dotnet restore
    - dotnet tool install -g Amazon.Lambda.Tools

stages:
    - deploy

deploy:
    stage: deploy
    script:
        - dotnet build
        - dotnet lambda deploy-serverless DotNetApiLambda --template serverless.template --s3-bucket $S3_BUCKET_NAME
            -- --aws-access-key-id $AWS_ACCESS_KEY_ID --aws-secret-key $AWS_SECRET_ACCESS_KEY --region us-east-1 --disable-interactive
